service: api-v2-jwt-auth

frameworkVersion: '3'

custom:
  logRetentionInDays: 7
  prune:
    automatic: true
    number: 1

functions:
  hello:
    handler: src/helloHandler.default
    events:
      - httpApi:
          method: GET
          path: /hello
          authorizer:
            name: jwtAuthorizer
  bonjour:
    handler: src/helloHandler.default
    events:
      - httpApi:
          method: GET
          path: /bonjour
          authorizer:
            name: jwtAuthorizer
            scopes:
              - client-credentials-flow-demo/bonjour.read


package:
  individually: true

provider:
  architecture: arm64
  deploymentBucket:
    name: com.reference-architecture.deploys
    maxPreviousDeploymentArtifacts: 5
    serverSideEncryption: AES256
  httpApi:
    authorizers:
      jwtAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_6sTyAz6FG
        audience:
          - 2vhsp03ghl5blivcgg9igrd44d
          - 78gj39v80jjacour5l5ls1vaeu
  name: aws
  region: ${opt:region, 'us-east-1'}
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  tags:
    lumigo:auto-trace: true

plugins:
  - serverless-esbuild
  - serverless-deployment-bucket
  - serverless-iam-roles-per-function
  - serverless-plugin-log-retention
  - serverless-prune-plugin

resources:
  - ${file(infrastructure/cognito.yml)}
