service: api-v2-jwt-auth

frameworkVersion: 3.x

custom:
  logRetentionInDays: 7
  prune:
    automatic: true
    number: 1

functions:
  hello:
    handler: src/helloHandler.default
    events:
      - httpApi:
          method: GET
          path: /hello
          authorizer:
            name: jwtAuthorizer
  bonjour:
    handler: src/helloHandler.default
    events:
      - httpApi:
          method: GET
          path: /bonjour
          authorizer:
            name: jwtAuthorizer
            scopes:
              - client-credentials-flow-demo/bonjour.read


package:
  individually: true

provider:
  architecture: arm64
  deploymentBucket:
    name: com.reference-architecture.deploys
    maxPreviousDeploymentArtifacts: 5
    serverSideEncryption: AES256
  httpApi:
    authorizers:
      jwtAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: https://cognito-idp.us-east-1.amazonaws.com/${cf:api-v2-jwt-auth-infra-dev.HttpApiAuthUserPoolId}
        audience:
          - ${cf:api-v2-jwt-auth-infra-dev.ScopedTestClientId}
          - ${cf:api-v2-jwt-auth-infra-dev.UnScopedTestClientId}
  name: aws
  region: ${opt:region, 'us-east-1'}
  runtime: nodejs22.x
  stage: ${opt:stage, 'dev'}
  logRetentionInDays: 7
  tags:
    lumigo:auto-trace: 'true'

plugins:
  - serverless-esbuild
  - serverless-deployment-bucket
  - serverless-iam-roles-per-function
  - serverless-plugin-log-retention
  - serverless-prune-plugin
